### PR TITLE
20161216 fix bijoux texts

### PR DESCRIPTION
**Pull request by vinyll**
cf mail "Fwd: proto bijou à valider"

### CODE REVIEW

**Comment by davidbgk** [comment]
Should be issued against `dev`?

**Comment by davidbgk** [comment]
(maybe we should change the default branch in repo's settings ;) )

**Comment by vinyll** [comment]
It should be against _dev_ indeed. I'll just merge using git instead of Github.

**Review by davidbgk — APPROVED** [review]
👍

**Comment by vinyll** [comment]
merged by hand

**Pull request closed without merging**
